title: TechDoc
description: "Technical Documentation Project"
#theme: jekyll-theme-slate
remote_theme: pages-themes/leap-day@v0.2.0
markdown: kramdown


toc:
  - title: Security
    subfolderitems:
      - page: Encryption
        url: /security/encryption.html
      - page: Asymmetric Keys
        url: /security/asymmetric-keys.html
      - page: Thing 3
        url: /thing3.html

# Navigation structure
nav:
  - Home: index.md
  - Security:
      - Encryption: security/encryption.md
      - Public & Private Keys: security/asymmetric-keys.md
  - Development:
      - Setup: development/setup.md
      - Architecture: development/architecture.md

header_pages:
  - Home: index.md

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-toc
