title: TechDoc
description: "Technical Documentation Project"
theme: just-the-docs
nav_enabled: true
heading_anchors: true
search_enabled: true

collections:
  docs:
    output: true
    permalink: /:collection/:path/

#just-the-docs theme documentation https://just-the-docs.com