title: TechDoc
description: "Technical Documentation Project"
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: light

collections:
  docs:
    output: true
    permalink: /:collection/:path/
