title: TechDoc
description: "Technical Documentation Project"
theme: just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

collections:
  docs:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap


#just-the-docs theme documentation https://just-the-docs.com